// Type definition for a school district
export interface District {
  name: string; // display name
  url: string; // HAC or portal URL
}

export const districts: District[] = [
  { name: "Tuslaw Local", url: "hac.sparcc.org" },
  { name: "Windham Exempted Village", url: "hac.sparcc.org" },
  { name: "Academics Plus Charter", url: "hac23.esp.k12.ar.us" },
  { name: "Academies of Math &amp; Science", url: "hac23.esp.k12.ar.us" },
  { name: "Alma SD", url: "hac23.esp.k12.ar.us" },
  { name: "Alpena School district", url: "hac23.esp.k12.ar.us" },
  { name: "Ar School For The Blind SD", url: "hac23.esp.k12.ar.us" },
  {
    name: "Arch Ford Education Service Cooperative",
    url: "hac23.esp.k12.ar.us",
  },
  { name: "Arkadelphia SD", url: "hac23.esp.k12.ar.us" },
  { name: "Arkansas Arts Academy", url: "hac23.esp.k12.ar.us" },
  { name: "Arkansas Connections Academy", url: "hac23.esp.k12.ar.us" },
  { name: "Arkansas Lighthouse Charter Schools", url: "hac23.esp.k12.ar.us" },
  { name: "Magazine SD", url: "hac23.esp.k12.ar.us" },
  { name: "Magnet Cove SD", url: "hac23.esp.k12.ar.us" },
  { name: "Magnolia SD", url: "hac23.esp.k12.ar.us" },
  { name: "Malvern SD", url: "hac23.esp.k12.ar.us" },
  { name: "Mammoth Spring SD", url: "hac23.esp.k12.ar.us" },
  { name: "Manila SD", url: "hac23.esp.k12.ar.us" },
  { name: "Mansfield SD", url: "hac23.esp.k12.ar.us" },
  { name: "Marion SD", url: "hac23.esp.k12.ar.us" },
  { name: "Marked Tree SD", url: "hac23.esp.k12.ar.us" },
  { name: "Marmaduke SD", url: "hac23.esp.k12.ar.us" },
  { name: "Marvell-Elaine SD", url: "hac23.esp.k12.ar.us" },
  { name: "Mayflower SD", url: "hac23.esp.k12.ar.us" },
  { name: "Maynard SD", url: "hac23.esp.k12.ar.us" },
  { name: "McCrory SD", url: "hac23.esp.k12.ar.us" },
  { name: "McGehee SD", url: "hac23.esp.k12.ar.us" },
  { name: "Melbourne SD", url: "hac23.esp.k12.ar.us" },
  { name: "Mena SD", url: "hac23.esp.k12.ar.us" },
  { name: "Midland SD", url: "hac23.esp.k12.ar.us" },
  { name: "Mineral Springs SD", url: "hac23.esp.k12.ar.us" },
  { name: "Monticello SD", url: "hac23.esp.k12.ar.us" },
  { name: "Mount Ida SD", url: "hac23.esp.k12.ar.us" },
  { name: "Mountain Home SD", url: "hac23.esp.k12.ar.us" },
  { name: "Mountain Pine SD", url: "hac23.esp.k12.ar.us" },
  { name: "Mountain View SD", url: "hac23.esp.k12.ar.us" },
  { name: "Willamina Live", url: "wil41hac.eschoolplus.powerschool.com" },
  { name: "Alamo Heights Live", url: "esp41pwhac.eschoolplus.powerschool.com" },
  { name: "Bethel SD Live", url: "esp41pwhac.eschoolplus.powerschool.com" },
  {
    name: "Broken Arrow PS Live",
    url: "esp41pwhac.eschoolplus.powerschool.com",
  },
  {
    name: "Buckeye Union SD Live",
    url: "esp41pwhac.eschoolplus.powerschool.com",
  },
  { name: "Cleveland ISD Live", url: "esp41pwhac.eschoolplus.powerschool.com" },
  { name: "Denison ISD Live", url: "esp41pwhac.eschoolplus.powerschool.com" },
  {
    name: "Granada Hills Charter SD",
    url: "esp41pwhac.eschoolplus.powerschool.com",
  },
  {
    name: "Hood River County SD Live",
    url: "esp41pwhac.eschoolplus.powerschool.com",
  },
  {
    name: "Huntsville ISD Live",
    url: "esp41pwhac.eschoolplus.powerschool.com",
  },
  {
    name: "Kingsville ISD Live",
    url: "esp41pwhac.eschoolplus.powerschool.com",
  },
  { name: "Melissa ISD Live", url: "esp41pwhac.eschoolplus.powerschool.com" },
  {
    name: "Arkansas Military &amp; First Responders Academy",
    url: "hac23.esp.k12.ar.us",
  },
  {
    name: "Arkansas River Education Service Cooperative",
    url: "hac23.esp.k12.ar.us",
  },
  { name: "Arkansas School for the Deaf", url: "hac23.esp.k12.ar.us" },
  { name: "Arkansas Virtual Academy", url: "hac23.esp.k12.ar.us" },
  { name: "Armorel SD", url: "hac23.esp.k12.ar.us" },
  { name: "Ashdown SD", url: "hac23.esp.k12.ar.us" },
  { name: "Atkins SD", url: "hac23.esp.k12.ar.us" },
  { name: "Augusta SD", url: "hac23.esp.k12.ar.us" },
  { name: "Bald Knob SD", url: "hac23.esp.k12.ar.us" },
  { name: "Barton SD", url: "hac23.esp.k12.ar.us" },
  { name: "Batesville SD", url: "hac23.esp.k12.ar.us" },
  { name: "Frisco ISD", url: "hac.friscoisd.org" },
  { name: "McKinney ISD", url: "hac.mckinneyisd.net" },
  { name: "Round Rock ISD", url: "accesscenter.roundrockisd.org" },
  { name: "Irving ISD", url: "esphac.irvingisd.net" },
  { name: "Leander ISD", url: "lis-hac.eschoolplus.powerschool.com" },
  { name: "Tomball ISD", url: "grades.tomballisd.net" },
  { name: "Northside ISD", url: "hac.nisd.net" },
  { name: "Cypress Fairbanks ISD", url: "home-access.cfisd.net" },
  { name: "Katy ISD", url: "homeaccess.katyisd.org" },
  { name: "Denton ISD", url: "denhac.dentonisd.org" },
  { name: "Coppell ISD", url: "hac.coppellisd.com" },
  { name: "Killeen ISD", url: "esphac.killeenisd.org" },
  { name: "Carmel Live", url: "esp41pehac.eschoolplus.powerschool.com" },
  {
    name: "Chester Upland SD Live",
    url: "esp41pehac.eschoolplus.powerschool.com",
  },
  {
    name: "Chester Upland 2020",
    url: "esp41pehac.eschoolplus.powerschool.com",
  },
  {
    name: "Coatesville Area SD Live",
    url: "esp41pehac.eschoolplus.powerschool.com",
  },
  { name: "Conneaut SD Live", url: "esp41pehac.eschoolplus.powerschool.com" },
  { name: "Council Rock SD", url: "esp41pehac.eschoolplus.powerschool.com" },
  {
    name: "CSMI-Atlantic City Charter Live",
    url: "esp41pehac.eschoolplus.powerschool.com",
  },
  {
    name: "CSMI-Camden Charter Live",
    url: "esp41pehac.eschoolplus.powerschool.com",
  },
  {
    name: "CSMI-Chester Community Charter Live",
    url: "esp41pehac.eschoolplus.powerschool.com",
  },
  {
    name: "Franklin Regional Live",
    url: "esp41pehac.eschoolplus.powerschool.com",
  },
  {
    name: "Greater Latrobe SD Live",
    url: "esp41pehac.eschoolplus.powerschool.com",
  },
  {
    name: "Hudson City Schools",
    url: "esp41pehac.eschoolplus.powerschool.com",
  },
  { name: "Bradford SD", url: "hac23.esp.k12.ar.us" },
  { name: "Brinkley SD", url: "hac23.esp.k12.ar.us" },
  { name: "Brookland SD", url: "hac23.esp.k12.ar.us" },
  { name: "Bryant SD", url: "hac23.esp.k12.ar.us" },
  { name: "Buffalo Island Central SD", url: "hac23.esp.k12.ar.us" },
  { name: "Cabot SD", url: "hac23.esp.k12.ar.us" },
  { name: "Caddo Hills SD", url: "hac23.esp.k12.ar.us" },
  { name: "Calico Rock SD", url: "hac23.esp.k12.ar.us" },
  { name: "Camden Fairview SD", url: "hac23.esp.k12.ar.us" },
  { name: "Carlisle SD", url: "hac23.esp.k12.ar.us" },
  { name: "Cave City SD", url: "hac23.esp.k12.ar.us" },
  { name: "Cedar Ridge SD", url: "hac23.esp.k12.ar.us" },
  { name: "Bauxite SD", url: "hac23.esp.k12.ar.us" },
  { name: "Bay SD", url: "hac23.esp.k12.ar.us" },
  { name: "Bearden SD", url: "hac23.esp.k12.ar.us" },
  { name: "Beebe SD", url: "hac23.esp.k12.ar.us" },
  { name: "Benton SD", url: "hac23.esp.k12.ar.us" },
  { name: "Bentonville SD", url: "hac23.esp.k12.ar.us" },
  { name: "Bergman SD", url: "hac23.esp.k12.ar.us" },
  { name: "Berryville SD", url: "hac23.esp.k12.ar.us" },
  { name: "Bismarck SD", url: "hac23.esp.k12.ar.us" },
  { name: "Blevins SD", url: "hac23.esp.k12.ar.us" },
  { name: "Blytheville SD", url: "hac23.esp.k12.ar.us" },
  { name: "Booneville SD", url: "hac23.esp.k12.ar.us" },
  {
    name: "Nacogdoches ISD Live",
    url: "esp41pwhac.eschoolplus.powerschool.com",
  },
  { name: "Nederland ISD Live", url: "esp41pwhac.eschoolplus.powerschool.com" },
  { name: "RES PHS Live", url: "esp41pwhac.eschoolplus.powerschool.com" },
  { name: "RES TCP Live", url: "esp41pwhac.eschoolplus.powerschool.com" },
  {
    name: "St Bernards Parish Live",
    url: "esp41pwhac.eschoolplus.powerschool.com",
  },
  {
    name: "Texans Can Academies Live",
    url: "esp41pwhac.eschoolplus.powerschool.com",
  },
  {
    name: "Tuloso-Midway ISD Live",
    url: "esp41pwhac.eschoolplus.powerschool.com",
  },
  {
    name: "Vanguard Academy Live",
    url: "esp41pwhac.eschoolplus.powerschool.com",
  },
  { name: "PITeSchool_Live", url: "hac40.pps.k12.pa.us" },
  {
    name: "Aurora West SD Live",
    url: "esp41pehac.eschoolplus.powerschool.com",
  },
  {
    name: "Belvidere Community Unit School Dist#100",
    url: "esp41pehac.eschoolplus.powerschool.com",
  },
  {
    name: "Brookville ASD Live",
    url: "esp41pehac.eschoolplus.powerschool.com",
  },
  { name: "State College ASD", url: "homeaccess.scasd.org" },
  { name: "Alief ISD", url: "aliefhac1.aliefisd.net" },
  { name: "College Station ISD", url: "hac.csisd.org" },
  { name: "Los Fresnos Consolidated ISD", url: "eschoolhac.lfcisd.net" },
  { name: "Humble ISD", url: "eshac.humbleisd.net" },
  { name: "Ysleta ISD", url: "hac2.yisd.net" },
  { name: "Kingsville ISD", url: "hac.kingsvilleisd.com" },
  { name: "Mount Pleasant ISD", url: "hac.mpisd.net" },
  { name: "Everett Public Schools", url: "hac.everett.k12.wa.us" },
  { name: "Alum Rock USD", url: "hac.arusd.org" },
  { name: "Interboro SD", url: "hac.interborosd.org" },
  { name: "Harlingen Consolidated ISD", url: "harhac.hcisd.org" },
  {
    name: "Jserra Catholic HS Live",
    url: "esp41pehac.eschoolplus.powerschool.com",
  },
  {
    name: "Rockford Charter School Live",
    url: "esp41pehac.eschoolplus.powerschool.com",
  },
  { name: "South Park SD Live", url: "esp41pehac.eschoolplus.powerschool.com" },
  { name: "Toledo SD Live", url: "esp41pehac.eschoolplus.powerschool.com" },
  { name: "Academia Antonia Alonso", url: "hacdoe.doe.k12.de.us" },
  { name: "Academy of Dover Charter School", url: "hacdoe.doe.k12.de.us" },
  { name: "Appoquinimink SD", url: "hacdoe.doe.k12.de.us" },
  { name: "Brandywine SD", url: "hacdoe.doe.k12.de.us" },
  {
    name: "Bryan Allen Stevenson School of Excellence",
    url: "hacdoe.doe.k12.de.us",
  },
  { name: "Caesar Rodney", url: "hacdoe.doe.k12.de.us" },
  { name: "Campus Community Charter School", url: "hacdoe.doe.k12.de.us" },
  { name: "Cape Henlopen SD", url: "hacdoe.doe.k12.de.us" },
  { name: "Brown Local", url: "hac.sparcc.org" },
  { name: "Canton City SD", url: "hac.sparcc.org" },
  { name: "Canton Local", url: "hac.sparcc.org" },
  { name: "Crestwood Local", url: "hac.sparcc.org" },
  { name: "Fairless Local", url: "hac.sparcc.org" },
  { name: "Field Local", url: "hac.sparcc.org" },
  { name: "Jackson Local", url: "hac.sparcc.org" },
  { name: "Lake Local", url: "hac.sparcc.org" },
  { name: "Louisville City", url: "hac.sparcc.org" },
  { name: "Marlington Local", url: "hac.sparcc.org" },
  { name: "Mason City Schools", url: "hac.sparcc.org" },
  { name: "Massillon City", url: "hac.sparcc.org" },
  { name: "Massillon Digital", url: "hac.sparcc.org" },
  { name: "Minerva Local", url: "hac.sparcc.org" },
  { name: "North Canton", url: "hac.sparcc.org" },
  { name: "Northwest Local", url: "hac.sparcc.org" },
  { name: "Perry Local", url: "hac.sparcc.org" },
  { name: "Plain Local", url: "hac.sparcc.org" },
  { name: "R.G. Drage Career Ed", url: "hac.sparcc.org" },
  { name: "Ravenna", url: "hac.sparcc.org" },
  { name: "Sandy Valley Local", url: "hac.sparcc.org" },
  { name: "Stark County ESC", url: "hac.sparcc.org" },
  { name: "STRASBURG-FRANKLIN LOCAL SD", url: "hac.sparcc.org" },
  { name: "Streetsboro City", url: "hac.sparcc.org" },
  { name: "Capital SD", url: "hacdoe.doe.k12.de.us" },
  { name: "Charter School of New Castle", url: "hacdoe.doe.k12.de.us" },
  { name: "Charter School of Wilmington", url: "hacdoe.doe.k12.de.us" },
  { name: "Christina SD", url: "hacdoe.doe.k12.de.us" },
  { name: "Colonial SD", url: "hacdoe.doe.k12.de.us" },
  {
    name: "Delaware Academy of Public Safety and Security",
    url: "hacdoe.doe.k12.de.us",
  },
  { name: "Delaware College Preparatory Academy", url: "hacdoe.doe.k12.de.us" },
  { name: "Delaware Design-Lab High School", url: "hacdoe.doe.k12.de.us" },
  { name: "Delaware Military Academy", url: "hacdoe.doe.k12.de.us" },
  { name: "Delaware STEM Academy", url: "hacdoe.doe.k12.de.us" },
  { name: "Delmar SD", url: "hacdoe.doe.k12.de.us" },
  { name: "Corpus Christi ISD", url: "hac.ccisd.us" },
  { name: "Calvert County Public Schools", url: "hac.calvertnet.k12.md.us" },
  { name: "Centerville City SD", url: "hac.centerville.k12.oh.us" },
  { name: "Rockford Public Schools District 205", url: "hac.rps205.com" },
  { name: "Suffolk Public Schools", url: "hac.spsk12.net" },
  { name: "Northwest ISD", url: "hac.nisdtx.org" },
  { name: "Champaign Unit 4 SD", url: "hac.champaignschools.org" },
  { name: "Mastery Charter School", url: "hacnj.masterycharter.org" },
  { name: "Victoria ISD", url: "visdgrades.visd.net" },
  { name: "Hilliard City Schools", url: "homeaccess.hboe.org" },
  { name: "Spring ISD", url: "hac4.springisd.org" },
  { name: "Bryan ISD", url: "hac.bryanisd.org" },
  { name: "Lakota Local SD", url: "hac.lakotainline.com" },
  { name: "Carroll County Public Schools", url: "mystudent.carrollk12.org" },
  { name: "Tamalpais Union High SD", url: "home.tamdistrict.org" },
  { name: "St. Johns County SD", url: "homeaccess.stjohns.k12.fl.us" },
  { name: "Tacoma Public Schools", url: "espha.tacoma.k12.wa.us" },
  { name: "Community High SD 99", url: "hac.csd99.org" },
  { name: "St. Charles District 303", url: "istudent.d303.org" },
  { name: "Geneva CUSD", url: "eschoolhac.geneva304.org" },
  { name: "Neshaminy SD", url: "hac.neshaminy.org" },
  { name: "Dayton Public School", url: "hac4.dps.k12.oh.us" },
  { name: "Plainfield SD", url: "esp-has-1.psd202.org" },
  { name: "Brownsville ISD", url: "hac.bisd.us" },
  { name: "Irvington UFSD", url: "hac.lhric.org" },
  { name: "Eastchester", url: "hac.lhric.org" },
  { name: "Lakeland CSD", url: "hac.lhric.org" },
  { name: "MtVernonCSD", url: "hac.lhric.org" },
  { name: "Nanuet UFSD", url: "hac.lhric.org" },
  { name: "New Rochelle CSD", url: "hac.lhric.org" },
  { name: "Port Chester UFSD", url: "hac.lhric.org" },
  { name: "GreenburghCSD", url: "hac.lhric.org" },
  { name: "Greenburgh11", url: "hac.lhric.org" },
  { name: "GreenburghNorthCastleUFSD", url: "hac.lhric.org" },
  { name: "Hawthorne Cedar Knolls UFSD", url: "hac.lhric.org" },
  { name: "Alliance City", url: "hac.sparcc.org" },
  {
    name: "Springfield Township Live",
    url: "esp41pehac.eschoolplus.powerschool.com",
  },
  { name: "Union Area SD Live", url: "esp41pehac.eschoolplus.powerschool.com" },
  { name: "Upper Darby SD", url: "esp41pehac.eschoolplus.powerschool.com" },
  {
    name: "Upper Moreland Township SD",
    url: "esp41pehac.eschoolplus.powerschool.com",
  },
  { name: "Wayland PS Live", url: "esp41pehac.eschoolplus.powerschool.com" },
  {
    name: "West Chicago ESD #33 Live",
    url: "esp41pehac.eschoolplus.powerschool.com",
  },
  {
    name: "William Penn SD Live",
    url: "esp41pehac.eschoolplus.powerschool.com",
  },
  {
    name: "Windham Public Schools",
    url: "esp41pehac.eschoolplus.powerschool.com",
  },
  {
    name: "Yonkers Public Schools Live",
    url: "esp41pehac.eschoolplus.powerschool.com",
  },
  { name: "Carlynton SD Live", url: "esp41pehac.eschoolplus.powerschool.com" },
  { name: "Enfield Live", url: "esp41pehac.eschoolplus.powerschool.com" },
  {
    name: "Great Oaks Bridgeport Live",
    url: "esp41pehac.eschoolplus.powerschool.com",
  },
  {
    name: "Jefferson County Dubois Live",
    url: "esp41pehac.eschoolplus.powerschool.com",
  },
  {
    name: "Lower Moreland Live",
    url: "esp41pehac.eschoolplus.powerschool.com",
  },
  { name: "Parkland SD Live", url: "esp41pehac.eschoolplus.powerschool.com" },
  { name: "Pennsbury SD Live", url: "esp41pehac.eschoolplus.powerschool.com" },
  { name: "Pottstown Live", url: "esp41pehac.eschoolplus.powerschool.com" },
  {
    name: "Radnor Township SD Live",
    url: "esp41pehac.eschoolplus.powerschool.com",
  },
  { name: "Riverview SD", url: "esp41pehac.eschoolplus.powerschool.com" },
  { name: "Rose Tree Live", url: "esp41pehac.eschoolplus.powerschool.com" },
  {
    name: "Scranton City SD Live",
    url: "esp41pehac.eschoolplus.powerschool.com",
  },
  { name: "Souderton Area SD", url: "esp41pehac.eschoolplus.powerschool.com" },
  {
    name: "Speed SEJA SD #802 Live",
    url: "esp41pehac.eschoolplus.powerschool.com",
  },
  {
    name: "Springfield SD Live",
    url: "esp41pehac.eschoolplus.powerschool.com",
  },
  { name: "Prestige Academy", url: "hacdoe.doe.k12.de.us" },
  { name: "Providence Creek", url: "hacdoe.doe.k12.de.us" },
  { name: "Prison Education", url: "hacdoe.doe.k12.de.us" },
  { name: "Reach Academy for Girls", url: "hacdoe.doe.k12.de.us" },
  { name: "Red Clay Consolidated SD", url: "hacdoe.doe.k12.de.us" },
  { name: "Seaford SD", url: "hacdoe.doe.k12.de.us" },
  { name: "Smyrna SD", url: "hacdoe.doe.k12.de.us" },
  { name: "Sussex Academy of Arts and Sciences", url: "hacdoe.doe.k12.de.us" },
  { name: "Sussex Montessori School", url: "hacdoe.doe.k12.de.us" },
  { name: "Sussex Technical SD", url: "hacdoe.doe.k12.de.us" },
  { name: "The Delaware Met", url: "hacdoe.doe.k12.de.us" },
  { name: "Woodbridge SD", url: "hacdoe.doe.k12.de.us" },
  {
    name: "Wilbur D. Mills Education Service Cooperative",
    url: "hac23.esp.k12.ar.us",
  },
  { name: "Wonderview SD", url: "hac23.esp.k12.ar.us" },
  { name: "Woodlawn SD", url: "hac23.esp.k12.ar.us" },
  { name: "Wynne SD", url: "hac23.esp.k12.ar.us" },
  { name: "Yellville-Summit SD", url: "hac23.esp.k12.ar.us" },
  { name: "Aldine ISD", url: "hac.aldineisd.org" },
  { name: "HEB ISD", url: "homeaccess.hebisd.edu" },
  { name: "Central Dauphin Schools", url: "hac.cdschools.org" },
  { name: "Akron Public Schools", url: "homeaccess.akron.k12.oh.us" },
  { name: "East Meadow SD", url: "homeaccess.emufsd.us" },
  { name: "San Angelo ISD", url: "homeaccess.saisd.org" },
  { name: "Parma City SD", url: "homeaccess.parmacityschools.org" },
  { name: "St. Mary's County Public Schools", url: "hac.smcps.org" },
  { name: "Chula Vista Elementary SD", url: "homeaccesscenter.cvesd.org" },
  { name: "Hinsdale Central", url: "portal.hinsdale86.org" },
  { name: "Harford County Public Schools", url: "hac.hcps.org" },
  { name: "Midway ISD", url: "hac.midwayisd.org" },
  {
    name: "Muslim Eductional Trust Live",
    url: "wil41hac.eschoolplus.powerschool.com",
  },
  { name: "North Wasco Live", url: "wil4thac.eschoolplus.powerschool.com" },
  { name: "Oakridge Live", url: "wil4thac.eschoolplus.powerschool.com" },
  { name: "Pendleton Live", url: "wil41hac.eschoolplus.powerschool.com" },
  { name: "Perrydale Live", url: "wil4thac.eschoolplus.powerschool.com" },
  { name: "Sheridan Live", url: "wil4thac.eschoolplus.powerschool.com" },
  { name: "South Lane Live", url: "wil41hac.eschoolplus.powerschool.com" },
  { name: "St. Paul Live", url: "wil4thac.eschoolplus.powerschool.com" },
  { name: "Ukiah Live", url: "wil4thac.eschoolplus.powerschool.com" },
  { name: "WESD EI/ECSE Live", url: "wil41hac.eschoolplus.powerschool.com" },
  {
    name: "Willamette Career Academy Live",
    url: "wil4thac.eschoolplus.powerschool.com",
  },
  {
    name: "Willamette ESD Template41",
    url: "wil4thac.eschoolplus.powerschool.com",
  },
  { name: "Creswell Live", url: "wil41hac.eschoolplus.powerschool.com" },
  { name: "Crow-Applegate Live", url: "wil41hac.eschoolplus.powerschool.com" },
  { name: "Dallas Live", url: "wil41hac.eschoolplus.powerschool.com" },
  { name: "Dayton SD Live", url: "wil41hac.eschoolplus.powerschool.com" },
  { name: "Fern Ridge Live", url: "wil41hac.eschoolplus.powerschool.com" },
  { name: "Junction City Live", url: "wil41hac.eschoolplus.powerschool.com" },
  { name: "Klamath Live", url: "wil41hac.eschoolplus.powerschool.com" },
  { name: "Lane ESD Live", url: "wil41hac.eschoolplus.powerschool.com" },
  { name: "Lowell Live", url: "wil41hac.eschoolplus.powerschool.com" },
  { name: "Mapleton Live", url: "wil41hac.eschoolplus.powerschool.com" },
  { name: "Mckenzie Live", url: "wil41hac.eschoolplus.powerschool.com" },
  { name: "McMinnville Live", url: "wil41hac.eschoolplus.powerschool.com" },
  { name: "So. Conway County SD", url: "hac23.esp.k12.ar.us" },
  {
    name: "South Central Education Service Cooperative",
    url: "hac23.esp.k12.ar.us",
  },
  { name: "South Pike County SD", url: "hac23.esp.k12.ar.us" },
  { name: "South Side(Bee Branch) SD", url: "hac23.esp.k12.ar.us" },
  {
    name: "Southeast Arkansas Community Based Education Ctr",
    url: "hac23.esp.k12.ar.us",
  },
  {
    name: "Southeast Arkansas Education Service Cooperative",
    url: "hac23.esp.k12.ar.us",
  },
  { name: "Southside SD", url: "hac23.esp.k12.ar.us" },
  {
    name: "Southwest Arkansas Education Cooperative",
    url: "hac23.esp.k12.ar.us",
  },
  { name: "Spring Hill SD", url: "hac23.esp.k12.ar.us" },
  { name: "Springdale SD", url: "hac23.esp.k12.ar.us" },
  { name: "Star City SD", url: "hac23.esp.k12.ar.us" },
  { name: "El Dorado SD", url: "hac23.esp.k12.ar.us" },
  { name: "Elkins SD", url: "hac23.esp.k12.ar.us" },
  { name: "Emerson-Taylor-Bradley SD", url: "hac23.esp.k12.ar.us" },
  { name: "England SD", url: "hac23.esp.k12.ar.us" },
  { name: "eSTEM Public Charter School", url: "hac23.esp.k12.ar.us" },
  { name: "Eureka Springs SD", url: "hac23.esp.k12.ar.us" },
  {
    name: "Exalt Academy of Southwest Little Rock",
    url: "hac23.esp.k12.ar.us",
  },
  { name: "Farmington SD", url: "hac23.esp.k12.ar.us" },
  { name: "Fayetteville SD", url: "hac23.esp.k12.ar.us" },
  { name: "Flippin SD", url: "hac23.esp.k12.ar.us" },
  { name: "Fordyce SD", url: "hac23.esp.k12.ar.us" },
  { name: "Foreman SD", url: "hac23.esp.k12.ar.us" },
  { name: "Las Americas Aspira Academy", url: "hacdoe.doe.k12.de.us" },
  { name: "Laurel SD", url: "hacdoe.doe.k12.de.us" },
  { name: "Maurice Moyer", url: "hacdoe.doe.k12.de.us" },
  { name: "Milford", url: "hacdoe.doe.k12.de.us" },
  { name: "MOT Charter School", url: "hacdoe.doe.k12.de.us" },
  { name: "New Castle Votech", url: "hacdoe.doe.k12.de.us" },
  { name: "Newark Charter School", url: "hacdoe.doe.k12.de.us" },
  { name: "Odyssey Charter School", url: "hacdoe.doe.k12.de.us" },
  { name: "Part C Birth to 3 Program", url: "hacdoe.doe.k12.de.us" },
  { name: "Pencader Charter School", url: "hacdoe.doe.k12.de.us" },
  { name: "Polytech", url: "hacdoe.doe.k12.de.us" },
  { name: "Positive Outcomes", url: "hacdoe.doe.k12.de.us" },
  { name: "DSCYF", url: "hacdoe.doe.k12.de.us" },
  {
    name: "Early College High School at Delaware State University",
    url: "hacdoe.doe.k12.de.us",
  },
  { name: "East Side Charter School", url: "hacdoe.doe.k12.de.us" },
  { name: "Edison Charter School", url: "hacdoe.doe.k12.de.us" },
  { name: "First State Military Academy", url: "hacdoe.doe.k12.de.us" },
  { name: "First State Montessori Academy", url: "hacdoe.doe.k12.de.us" },
  { name: "Freire Charter School", url: "hacdoe.doe.k12.de.us" },
  { name: "Gateway Laboratory School", url: "hacdoe.doe.k12.de.us" },
  { name: "Great Oaks Charter School", url: "hacdoe.doe.k12.de.us" },
  { name: "Indian River SD", url: "hacdoe.doe.k12.de.us" },
  { name: "Kuumba Academy Charter School", url: "hacdoe.doe.k12.de.us" },
  { name: "Lake Forest", url: "hacdoe.doe.k12.de.us" },
  {
    name: "Dequeen-Mena Education Service Cooperative",
    url: "hac23.esp.k12.ar.us",
  },
  { name: "Dermott SD", url: "hac23.esp.k12.ar.us" },
  { name: "Des Arc SD", url: "hac23.esp.k12.ar.us" },
  { name: "Dewitt SD", url: "hac23.esp.k12.ar.us" },
  { name: "Dierks SD", url: "hac23.esp.k12.ar.us" },
  { name: "Division of Youth Services", url: "hac23.esp.k12.ar.us" },
  { name: "Dover School District", url: "hac23.esp.k12.ar.us" },
  { name: "Drew Central SD", url: "hac23.esp.k12.ar.us" },
  { name: "Dumas SD", url: "hac23.esp.k12.ar.us" },
  { name: "Earle SD", url: "hac23.esp.k12.ar.us" },
  { name: "East End SD", url: "hac23.esp.k12.ar.us" },
  { name: "East Poinsett County SD", url: "hac23.esp.k12.ar.us" },
  { name: "Salem SD", url: "hac23.esp.k12.ar.us" },
  {
    name: "ScholarMade Achievement Place of Arkansas",
    url: "hac23.esp.k12.ar.us",
  },
  {
    name: "School for Advanced Studies- Northwest Arkansas",
    url: "hac23.esp.k12.ar.us",
  },
  { name: "Scranton SD", url: "hac23.esp.k12.ar.us" },
  { name: "Searcy County SD", url: "hac23.esp.k12.ar.us" },
  { name: "Searcy SD", url: "hac23.esp.k12.ar.us" },
  { name: "Sheridan SD", url: "hac23.esp.k12.ar.us" },
  { name: "Shirley SD", url: "hac23.esp.k12.ar.us" },
  { name: "Siloam Springs SD", url: "hac23.esp.k12.ar.us" },
  { name: "Sloan-Hendrix SD", url: "hac23.esp.k12.ar.us" },
  { name: "Smackover-Norphlet SD", url: "hac23.esp.k12.ar.us" },
  {
    name: "LaSalle-Peru Township High School District 120",
    url: "ehome.I|phs.org",
  },
  {
    name: "Evanston Township High School District 202",
    url: "hac.eths.k12.il.us",
  },
  {
    name: "Leyden Community High School District 212",
    url: "hac.leyden212.org",
  },
  { name: "LaPorte ISD", url: "hac.lpisd.org" },
  {
    name: "Pharr-San Juan-Alamo Independent School District",
    url: "homeaccess.psjaisd.us",
  },
  { name: "Lake Park High School District 108", url: "ehome.I|Iphs.org" },
  { name: "Bethel Park SD", url: "bpk-hac.eschoolplus.powerschool.com" },
  { name: "San Marcos Consolidated ISD", url: "homeaccess.smcisd.net" },
  { name: "Conroe ISD", url: "hac.conroeisd.net" },
  { name: "Cleveland ISD", url: "eshac.ctxisd.org" },
  { name: "Blachly Live", url: "wil4thac.eschoolplus.powerschool.com" },
  { name: "Forrest City SD", url: "hac23.esp.k12.ar.us" },
  { name: "Fort Smith SD", url: "hac23.esp.k12.ar.us" },
  { name: "Fouke SD", url: "hac23.esp.k12.ar.us" },
  {
    name: "Founders Classical Academies of Arkansas",
    url: "hac23.esp.k12.ar.us",
  },
  { name: "Fountain Lake SD", url: "hac23.esp.k12.ar.us" },
  { name: "Friendship Aspire Academies Arkansas", url: "hac23.esp.k12.ar.us" },
  { name: "Future School of Fort Smith", url: "hac23.esp.k12.ar.us" },
  { name: "Garfield Scholars Academy", url: "hac23.esp.k12.ar.us" },
  { name: "Genoa Central SD", url: "hac23.esp.k12.ar.us" },
  { name: "Gentry SD", url: "hac23.esp.k12.ar.us" },
  { name: "Glen Rose SD", url: "hac23.esp.k12.ar.us" },
  { name: "Gosnell SD", url: "hac23.esp.k12.ar.us" },
  { name: "Strong-Huttig SD", url: "hac23.esp.k12.ar.us" },
  { name: "Stuttgart SD", url: "hac23.esp.k12.ar.us" },
  { name: "Success SD", url: "hac23.esp.k12.ar.us" },
  { name: "Texarkana SD", url: "hac23.esp.k12.ar.us" },
  { name: "The Excel Center", url: "hac23.esp.k12.ar.us" },
  { name: "Trumann SD", url: "hac23.esp.k12.ar.us" },
  { name: "Two Rivers SD", url: "hac23.esp.k12.ar.us" },
  { name: "Valley Springs SD", url: "hac23.esp.k12.ar.us" },
  { name: "Valley View SD", url: "hac23.esp.k12.ar.us" },
  { name: "Van Buren SD", url: "hac23.esp.k12.ar.us" },
  { name: "Vilonia SD", url: "hac23.esp.k12.ar.us" },
  { name: "Viola SD", url: "hac23.esp.k12.ar.us" },
  { name: "Waldron SD", url: "hac23.esp.k12.ar.us" },
  { name: "Warren SD", url: "hac23.esp.k12.ar.us" },
  { name: "Watson Chapel SD", url: "hac23.esp.k12.ar.us" },
  { name: "West Fork SD", url: "hac23.esp.k12.ar.us" },
  { name: "West Memphis SD", url: "hac23.esp.k12.ar.us" },
  { name: "West Side (Cleburne County) SD", url: "hac23.esp.k12.ar.us" },
  { name: "Western Yell County SD", url: "hac23.esp.k12.ar.us" },
  { name: "Westside Consolidated SD", url: "hac23.esp.k12.ar.us" },
  { name: "Westside(Johnson County) SD", url: "hac23.esp.k12.ar.us" },
  { name: "Westwind School for Performing Arts", url: "hac23.esp.k12.ar.us" },
  { name: "White County Central SD", url: "hac23.esp.k12.ar.us" },
  { name: "White Hall SD", url: "hac23.esp.k12.ar.us" },
  { name: "Graduate Arkansas", url: "hac23.esp.k12.ar.us" },
  { name: "Gravette SD", url: "hac23.esp.k12.ar.us" },
  {
    name: "Great Rivers Education Service Cooperative",
    url: "hac23.esp.k12.ar.us",
  },
  { name: "Green Forest SD", url: "hac23.esp.k12.ar.us" },
  { name: "Greenbrier SD", url: "hac23.esp.k12.ar.us" },
  { name: "Greene County Tech SD", url: "hac23.esp.k12.ar.us" },
  { name: "Greenland SD", url: "hac23.esp.k12.ar.us" },
  { name: "Greenwood SD", url: "hac23.esp.k12.ar.us" },
  { name: "Gurdon SD", url: "hac23.esp.k12.ar.us" },
  {
    name: "Guy Fenter Education Service Cooperative",
    url: "hac23.esp.k12.ar.us",
  },
  { name: "Guy-Perkins SD", url: "hac23.esp.k12.ar.us" },
  { name: "Lake Hamilton SD", url: "hac23.esp.k12.ar.us" },
  { name: "Lakeside (Chicot County) SD", url: "hac23.esp.k12.ar.us" },
  { name: "Lakeside (Garland County) SD", url: "hac23.esp.k12.ar.us" },
  { name: "Lamar SD", url: "hac23.esp.k12.ar.us" },
  { name: "Lavaca SD", url: "hac23.esp.k12.ar.us" },
  { name: "Lawrence County SD", url: "hac23.esp.k12.ar.us" },
  { name: "Lead Hill SD", url: "hac23.esp.k12.ar.us" },
  { name: "Lee County SD", url: "hac23.esp.k12.ar.us" },
  { name: "Lincoln Consolidated SD", url: "hac23.esp.k12.ar.us" },
  { name: "LISA Academy", url: "hac23.esp.k12.ar.us" },
  { name: "Little Rock SD", url: "hac23.esp.k12.ar.us" },
  { name: "Lonoke SD", url: "hac23.esp.k12.ar.us" },
  { name: "Premier High Schools of Arkansas", url: "hac23.esp.k12.ar.us" },
  { name: "Prescott SD", url: "hac23.esp.k12.ar.us" },
  { name: "Pulaski County Special SD", url: "hac23.esp.k12.ar.us" },
  { name: "Quitman SD", url: "hac23.esp.k12.ar.us" },
  { name: "Rector SD", url: "hac23.esp.k12.ar.us" },
  {
    name: "Responsive Ed Solutions Premier High School of Springdale",
    url: "hac23.esp.k12.ar.us",
  },
  { name: "Rivercrest SD 57", url: "hac23.esp.k12.ar.us" },
  { name: "Riverside SD", url: "hac23.esp.k12.ar.us" },
  { name: "Riverview SD", url: "hac23.esp.k12.ar.us" },
  { name: "Rogers SD", url: "hac23.esp.k12.ar.us" },
  { name: "Rose Bud SD", url: "hac23.esp.k12.ar.us" },
  { name: "Russellville SD", url: "hac23.esp.k12.ar.us" },
  { name: "Paragould SD", url: "hac23.esp.k12.ar.us" },
  { name: "Paris SD", url: "hac23.esp.k12.ar.us" },
  { name: "Parkers Chapel SD", url: "hac23.esp.k12.ar.us" },
  { name: "Pea Ridge SD", url: "hac23.esp.k12.ar.us" },
  { name: "Perryville SD", url: "hac23.esp.k12.ar.us" },
  { name: "Piggott SD", url: "hac23.esp.k12.ar.us" },
  { name: "Pine Bluff SD", url: "hac23.esp.k12.ar.us" },
  {
    name: "Pinecrest Preparatory Academy Fayetteville",
    url: "hac23.esp.k12.ar.us",
  },
  { name: "Pocahontas SD", url: "hac23.esp.k12.ar.us" },
  { name: "Pottsville SD", url: "hac23.esp.k12.ar.us" },
  { name: "Poyen SD", url: "hac23.esp.k12.ar.us" },
  { name: "Prairie Grove SD", url: "hac23.esp.k12.ar.us" },
  { name: "IOTA Leadership Academy Elementary", url: "hac23.esp.k12.ar.us" },
  { name: "IOTA Leadership Academy Middle School", url: "hac23.esp.k12.ar.us" },
  { name: "Izard County Consolidated SD", url: "hac23.esp.k12.ar.us" },
  { name: "Jackson County SD", url: "hac23.esp.k12.ar.us" },
  { name: "Jacksonville-North Pulaski SD", url: "hac23.esp.k12.ar.us" },
  { name: "Jasper SD", url: "hac23.esp.k12.ar.us" },
  { name: "Jessieville SD", url: "hac23.esp.k12.ar.us" },
  { name: "Jonesboro SD", url: "hac23.esp.k12.ar.us" },
  { name: "Junction City SD", url: "hac23.esp.k12.ar.us" },
  { name: "Kipp: Delta Public Schools", url: "hac23.esp.k12.ar.us" },
  { name: "Kirby SD", url: "hac23.esp.k12.ar.us" },
  { name: "Lafayette County SD", url: "hac23.esp.k12.ar.us" },
  { name: "Cedarville SD", url: "hac23.esp.k12.ar.us" },
  { name: "Centerpoint SD", url: "hac23.esp.k12.ar.us" },
  { name: "Charleston SD", url: "hac23.esp.k12.ar.us" },
  {
    name: "CIVICA Career and Collegiate Academy Bentonville",
    url: "hac23.esp.k12.ar.us",
  },
  { name: "Clarendon SD", url: "hac23.esp.k12.ar.us" },
  { name: "Clarksville SD", url: "hac23.esp.k12.ar.us" },
  { name: "Cleveland County SD", url: "hac23.esp.k12.ar.us" },
  { name: "Clinton SD", url: "hac23.esp.k12.ar.us" },
  { name: "Concord SD", url: "hac23.esp.k12.ar.us" },
  { name: "Conway SD", url: "hac23.esp.k12.ar.us" },
  { name: "Corning SD", url: "hac23.esp.k12.ar.us" },
  { name: "Cossatot River SD", url: "hac23.esp.k12.ar.us" },
  { name: "Mountainburg SD", url: "hac23.esp.k12.ar.us" },
  { name: "Mt. Vernon/Enola SD", url: "hac23.esp.k12.ar.us" },
  { name: "Mulberry-Pleasant View Bi-County SD", url: "hac23.esp.k12.ar.us" },
  { name: "Nashville SD", url: "hac23.esp.k12.ar.us" },
  { name: "Nemo Vista SD", url: "hac23.esp.k12.ar.us" },
  { name: "Nettleton SD", url: "hac23.esp.k12.ar.us" },
  { name: "Nevada SD", url: "hac23.esp.k12.ar.us" },
  { name: "Newport SD", url: "hac23.esp.k12.ar.us" },
  { name: "Norfork SD", url: "hac23.esp.k12.ar.us" },
  { name: "North Little Rock SD", url: "hac23.esp.k12.ar.us" },
  {
    name: "Northcentral Arkansas Education Service Coop",
    url: "hac23.esp.k12.ar.us",
  },
  { name: "Haas Hall Academy", url: "hac23.esp.k12.ar.us" },
  { name: "Hackett SD", url: "hac23.esp.k12.ar.us" },
  { name: "Hamburg SD", url: "hac23.esp.k12.ar.us" },
  { name: "Hampton SD", url: "hac23.esp.k12.ar.us" },
  { name: "Harmony Grove (Quachitia County) SD", url: "hac23.esp.k12.ar.us" },
  { name: "Harmony Grove (Saline County) SD", url: "hac23.esp.k12.ar.us" },
  { name: "Harrisburg SD", url: "hac23.esp.k12.ar.us" },
  { name: "Harrison SD", url: "hac23.esp.k12.ar.us" },
  { name: "Hazen SD", url: "hac23.esp.k12.ar.us" },
  { name: "Heber Springs SD", url: "hac23.esp.k12.ar.us" },
  { name: "Hector SD", url: "hac23.esp.k12.ar.us" },
  { name: "Helena-West Helena SD", url: "hac23.esp.k12.ar.us" },
  { name: "Hermitage SD", url: "hac23.esp.k12.ar.us" },
  { name: "Highland SD", url: "hac23.esp.k12.ar.us" },
  { name: "Hillcrest SD", url: "hac23.esp.k12.ar.us" },
  { name: "Hope Academy of Northwest Arkansas", url: "hac23.esp.k12.ar.us" },
  { name: "Hope SD", url: "hac23.esp.k12.ar.us" },
  { name: "Horatio SD", url: "hac23.esp.k12.ar.us" },
  { name: "Hot Springs SD", url: "hac23.esp.k12.ar.us" },
  { name: "Hoxie SD", url: "hac23.esp.k12.ar.us" },
  { name: "Huntsville SD", url: "hac23.esp.k12.ar.us" },
  { name: "ID Management", url: "hac23.esp.k12.ar.us" },
  { name: "Imboden Area Charter School", url: "hac23.esp.k12.ar.us" },
  { name: "Institute for the Creative Arts", url: "hac23.esp.k12.ar.us" },
  {
    name: "Northeast Arkansas Education Cooperative",
    url: "hac23.esp.k12.ar.us",
  },
  {
    name: "Northwest Arkansas Education Service Cooperative",
    url: "hac23.esp.k12.ar.us",
  },
  { name: "Omaha SD", url: "hac23.esp.k12.ar.us" },
  { name: "Osceola SD", url: "hac23.esp.k12.ar.us" },
  { name: "Ouachita River SD", url: "hac23.esp.k12.ar.us" },
  { name: "Ouachita SD", url: "hac23.esp.k12.ar.us" },
  { name: "Ozark Mountain SD", url: "hac23.esp.k12.ar.us" },
  { name: "Ozark SD", url: "hac23.esp.k12.ar.us" },
  {
    name: "Ozarks Unlimited Resource Service Cooperative",
    url: "hac23.esp.k12.ar.us",
  },
  { name: "Palestine-Wheatley SD", url: "hac23.esp.k12.ar.us" },
  { name: "Pangburn SD", url: "hac23.esp.k12.ar.us" },
  { name: "Cotter SD", url: "hac23.esp.k12.ar.us" },
  { name: "County Line SD", url: "hac23.esp.k12.ar.us" },
  { name: "Cross County SD", url: "hac23.esp.k12.ar.us" },
  { name: "Crossett SD", url: "hac23.esp.k12.ar.us" },
  {
    name: "Crowley's Ridge Education Service Cooperative",
    url: "hac23.esp.k12.ar.us",
  },
  { name: "Cutter Morning Star SD", url: "hac23.esp.k12.ar.us" },
  { name: "Danville SD", url: "hac23.esp.k12.ar.us" },
  { name: "Dardanelle SD", url: "hac23.esp.k12.ar.us" },
  { name: "Dawson Education Service Cooperative", url: "hac23.esp.k12.ar.us" },
  { name: "Decatur SD", url: "hac23.esp.k12.ar.us" },
  { name: "Deer-Mount Judea SD", url: "hac23.esp.k12.ar.us" },
  { name: "DeQueen SD", url: "hac23.esp.k12.ar.us" },
];

